import { NgModule } from "@angular/core";
import { CommonModule } from '@angular/common';
import {
  MatGridListModule,
  MatFormFieldModule,
  MatInputModule,
  MatRadioModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatSelectModule,
  MatCheckboxModule,
  MatButtonModule,
  MatToolbarModule,
  MatSidenavModule,
  MatListModule,
  MatIconModule,
  MatMenuModule,
  // MatSnackBarModule,
  // MatDialogModule,
  // MatTableModule,
  // MatPaginatorModule,
  // MatSortModule,
  // MatTabsModule,
   MatCardModule,
  // MatFormField,
  // MatProgressSpinnerModule,
  // MatSliderModule,
  // MatDividerModule
} from "@angular/material";


@NgModule({
  imports: [
    CommonModule,
    MatGridListModule,
    MatFormFieldModule,
    MatInputModule,
    MatRadioModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSelectModule,
    MatCheckboxModule,
    MatButtonModule,
    MatToolbarModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatMenuModule,
    // MatSnackBarModule,
    // MatDialogModule,
    // MatTableModule,
    // MatPaginatorModule,
    // MatSortModule,
    // MatTabsModule,
     MatCardModule,
    // MatFormField,
    // MatProgressSpinnerModule,
    // MatSliderModule,
    // MatDividerModule
  ],
  exports: [
    CommonModule,
    MatGridListModule,
    MatFormFieldModule,
    MatInputModule,
    MatRadioModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSelectModule,
    MatCheckboxModule,
    MatButtonModule,
    MatToolbarModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatMenuModule,
    // MatSnackBarModule,
    // MatDialogModule,
    // MatTableModule,
    // MatPaginatorModule,
    // MatSortModule,
    // MatTabsModule,
     MatCardModule,
    // MatFormField,
    // MatProgressSpinnerModule,
    // MatSliderModule,
    // MatDividerModule
  ]
})
export class MaterialModule { }